global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:7301"]
        labels: { service: gateway }

  - job_name: escrow-manager
    static_configs:
      - targets: ["escrow-manager:9090"]
        labels: { service: escrow-manager }
