#!/usr/bin/env bash
# Pull verified Horizon contract addresses from the authoritative source
# (graphprotocol/contracts address book) into config/addresses.env, so operators
# never hand-copy an address. Reads a local clone if CONTRACTS_DIR is set,
# otherwise fetches the JSON from GitHub at CONTRACTS_REF (default: main).
#
#   ./scripts/fetch-addresses.sh            # Arbitrum One (42161) from GitHub main
#   CHAIN_ID=42161 CONTRACTS_REF=v7.1.2 ./scripts/fetch-addresses.sh
#   CONTRACTS_DIR=~/Projects/graph-contracts ./scripts/fetch-addresses.sh
set -euo pipefail
cd "$(dirname "$0")/.."

CHAIN_ID="${CHAIN_ID:-42161}"
CONTRACTS_REF="${CONTRACTS_REF:-main}"
OUT="config/addresses.env"

command -v python3 >/dev/null || { echo "ERROR: python3 required." >&2; exit 1; }

fetch() { # package -> stdout JSON
  local pkg="$1"
  if [ -n "${CONTRACTS_DIR:-}" ]; then
    cat "$CONTRACTS_DIR/packages/$pkg/addresses.json"
  else
    curl -fsSL "https://raw.githubusercontent.com/graphprotocol/contracts/$CONTRACTS_REF/packages/$pkg/addresses.json"
  fi
}

echo "Reading Horizon + SubgraphService address books for chain $CHAIN_ID (ref: ${CONTRACTS_DIR:-$CONTRACTS_REF})..."
HORIZON_JSON="$(fetch horizon)"
SUBSVC_JSON="$(fetch subgraph-service)"

export CHAIN_ID HORIZON_JSON SUBSVC_JSON
python3 - "$OUT" <<'PY'
import json, os, sys
chain = os.environ["CHAIN_ID"]
horizon = json.loads(os.environ["HORIZON_JSON"])
subsvc  = json.loads(os.environ["SUBSVC_JSON"])

def addr(book, key):
    entry = book.get(chain, {}).get(key)
    if entry is None:
        sys.exit(f"ERROR: {key} not found for chain {chain} in address book")
    a = entry.get("address") if isinstance(entry, dict) else entry
    if not (isinstance(a, str) and a.startswith("0x") and len(a) == 42):
        sys.exit(f"ERROR: {key} for chain {chain} is not a valid address: {a!r}")
    return a

fields = {
    "GRT":                   addr(horizon, "L2GraphToken"),
    "GRAPH_TALLY_COLLECTOR": addr(horizon, "GraphTallyCollector"),
    "PAYMENTS_ESCROW":       addr(horizon, "PaymentsEscrow"),
    "CONTROLLER":            addr(horizon, "Controller"),
    "SUBGRAPH_SERVICE":      addr(subsvc,  "SubgraphService"),
    "DISPUTE_MANAGER":       addr(subsvc,  "DisputeManager"),
}
with open(sys.argv[1], "w") as f:
    f.write(f"# Auto-generated by fetch-addresses.sh — DO NOT hand-edit. chain={chain}\n")
    for k, v in fields.items():
        f.write(f"{k}={v}\n")
        print(f"  {k:22} {v}")
PY

echo "Wrote $OUT"
